# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-08 05:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Anwser',
            new_name='Answer',
        ),
    ]
