# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-08 16:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0002_auto_20160808_0528'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='session',
            field=models.CharField(default='', max_length=200),
        ),
    ]
